export const presetsData = [
  {
    "bankPatch": "1-1",
    "soundNameCategory": "Mellow Sub Octave Pluck",
    "waveformOscType": "Saw + Sub",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "Mid",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "Low",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Delay 2",
    "notesDescription": "Mellow Sub Octave Pluck: (Good for Deadmau5)"
  },
  {
    "bankPatch": "1-2",
    "soundNameCategory": "Bright Detuned Saw Pluck",
    "waveformOscType": "Unison Saw",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "High",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "Low",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Delay 2",
    "notesDescription": "Bright Detuned Saw Pluck: (Good for Avicii)"
  },
  {
    "bankPatch": "1-3",
    "soundNameCategory": "Fat Square Lead / Bass",
    "waveformOscType": "Unison Square",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "Low",
    "attack": "Fast",
    "decay": "Fast",
    "sustain": "Max",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Reverb 2",
    "notesDescription": "Fat Square Lead / Bass: (Good for Chiptune)"
  },
  {
    "bankPatch": "1-4",
    "soundNameCategory": "Soft Analog Square Pluck",
    "waveformOscType": "Square",
    "filterFreq": "Low",
    "resonance": "Low",
    "envMod": "Mid",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "Low",
    "release": "Fast",
    "chorus": "Chorus 1",
    "delayReverb": "Reverb 1",
    "notesDescription": "Soft Analog Square Pluck: (Good for Lofi)"
  },
  {
    "bankPatch": "1-5",
    "soundNameCategory": "Resonant Acid Bass",
    "waveformOscType": "Saw",
    "filterFreq": "Low",
    "resonance": "Max",
    "envMod": "High",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "Low",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Off",
    "notesDescription": "Resonant Acid Bass: (Good for 303 emulation)"
  },
  {
    "bankPatch": "1-6",
    "soundNameCategory": "Deep Sub Bass",
    "waveformOscType": "Sub",
    "filterFreq": "Low",
    "resonance": "Low",
    "envMod": "Off",
    "attack": "Fast",
    "decay": "Max",
    "sustain": "Max",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Off",
    "notesDescription": "Deep Sub Bass: (Clean fundamental tone)"
  },
  {
    "bankPatch": "1-7",
    "soundNameCategory": "Evolving Filter Pad",
    "waveformOscType": "Unison Saw",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "Mid",
    "attack": "Slow",
    "decay": "Max",
    "sustain": "Max",
    "release": "Mid",
    "chorus": "Chorus 2",
    "delayReverb": "Reverb 4",
    "notesDescription": "Evolving Filter Pad: (Ambient Swell)"
  },
  {
    "bankPatch": "1-8",
    "soundNameCategory": "Bright 80s Polysynth Keys",
    "waveformOscType": "Saw + Square",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "Low",
    "attack": "Fast",
    "decay": "Max",
    "sustain": "Max",
    "release": "Mid",
    "chorus": "Chorus 2",
    "delayReverb": "Reverb 2",
    "notesDescription": "Bright 80s Polysynth Keys: (Classic Juno sound)"
  },
  {
    "bankPatch": "2-1",
    "soundNameCategory": "Hollow Square Pluck",
    "waveformOscType": "Square",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "Mid",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "Low",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Delay 1",
    "notesDescription": "Hollow Square Pluck"
  },
  {
    "bankPatch": "2-2",
    "soundNameCategory": "Percussive Organ Keys",
    "waveformOscType": "Multi-Square",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "Fast",
    "attack": "Fast",
    "decay": "Fast",
    "sustain": "Max",
    "release": "Fast",
    "chorus": "Chorus 1",
    "delayReverb": "Reverb 1",
    "notesDescription": "Percussive Organ Keys: (House music stabs)"
  },
  {
    "bankPatch": "2-3",
    "soundNameCategory": "Detuned PWM Pad",
    "waveformOscType": "PWM Saw",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "Low",
    "attack": "Slow",
    "decay": "Max",
    "sustain": "Max",
    "release": "Mid",
    "chorus": "Chorus 2",
    "delayReverb": "Reverb 3",
    "notesDescription": "Detuned PWM Pad: (Thick texture)"
  },
  {
    "bankPatch": "2-4",
    "soundNameCategory": "Snappy FM-Style Bass",
    "waveformOscType": "Square + Sub",
    "filterFreq": "Low",
    "resonance": "Mid",
    "envMod": "High",
    "attack": "Fast",
    "decay": "Fast",
    "sustain": "Low",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Off",
    "notesDescription": "Snappy FM-Style Bass: (Metallic attack)"
  },
  {
    "bankPatch": "2-5",
    "soundNameCategory": "Bright Phasey Strings",
    "waveformOscType": "Unison Saw",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "Off",
    "attack": "Mid",
    "decay": "Max",
    "sustain": "Max",
    "release": "Mid",
    "chorus": "Chorus 2",
    "delayReverb": "Reverb 2",
    "notesDescription": "Bright Phasey Strings: (String Machine emulation)"
  },
  {
    "bankPatch": "2-6",
    "soundNameCategory": "Lo-Fi Noise Lead",
    "waveformOscType": "Saw + Noise",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "Mid",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "Max",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Delay 3",
    "notesDescription": "Lo-Fi Noise Lead: (Vintage/textured)"
  },
  {
    "bankPatch": "2-7",
    "soundNameCategory": "Dark Ambient Pad",
    "waveformOscType": "Square",
    "filterFreq": "Low",
    "resonance": "Low",
    "envMod": "Low",
    "attack": "Slow",
    "decay": "Max",
    "sustain": "Max",
    "release": "Slow",
    "chorus": "Chorus 1",
    "delayReverb": "Reverb 4",
    "notesDescription": "Dark Ambient Pad: (Warm deep swell)"
  },
  {
    "bankPatch": "2-8",
    "soundNameCategory": "Classic Unison Lead",
    "waveformOscType": "Super Saw",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "Low",
    "attack": "Fast",
    "decay": "Max",
    "sustain": "Max",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Delay 2",
    "notesDescription": "Classic Unison Lead: (Trance/Dance anthem)"
  },
  {
    "bankPatch": "3-1",
    "soundNameCategory": "Plucky Sine / Sub",
    "waveformOscType": "Sine + Sub",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "Mid",
    "attack": "Fast",
    "decay": "Fast",
    "sustain": "Low",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Reverb 1",
    "notesDescription": "Plucky Sine / Sub"
  },
  {
    "bankPatch": "3-2",
    "soundNameCategory": "Warm Analog Keys",
    "waveformOscType": "Saw",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "Low",
    "attack": "Fast",
    "decay": "Max",
    "sustain": "Max",
    "release": "Fast",
    "chorus": "Chorus 1",
    "delayReverb": "Reverb 2",
    "notesDescription": "Warm Analog Keys: (Classic polyphonic)"
  },
  {
    "bankPatch": "3-3",
    "soundNameCategory": "Sustained Bright Brass",
    "waveformOscType": "Unison Saw",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "Mid",
    "attack": "Mid",
    "decay": "Max",
    "sustain": "Max",
    "release": "Mid",
    "chorus": "Off",
    "delayReverb": "Reverb 2",
    "notesDescription": "Sustained Bright Brass: (Synth horn emulation)"
  },
  {
    "bankPatch": "3-4",
    "soundNameCategory": "Slap Bass",
    "waveformOscType": "Square",
    "filterFreq": "Mid",
    "resonance": "High",
    "envMod": "High",
    "attack": "Fast",
    "decay": "Fast",
    "sustain": "Low",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Off",
    "notesDescription": "Slap Bass: (Funk/percussive)"
  },
  {
    "bankPatch": "3-5",
    "soundNameCategory": "Slow Sweep Pad",
    "waveformOscType": "Saw",
    "filterFreq": "Low",
    "resonance": "Mid",
    "envMod": "High",
    "attack": "Slow",
    "decay": "Max",
    "sustain": "Max",
    "release": "Mid",
    "chorus": "Chorus 2",
    "delayReverb": "Reverb 3",
    "notesDescription": "Slow Sweep Pad: (Filter sweep)"
  },
  {
    "bankPatch": "3-6",
    "soundNameCategory": "Chiptune Triangle Lead",
    "waveformOscType": "Triangle",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "Off",
    "attack": "Fast",
    "decay": "Max",
    "sustain": "Max",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Delay 1",
    "notesDescription": "Chiptune Triangle Lead"
  },
  {
    "bankPatch": "3-7",
    "soundNameCategory": "Glassy Digital Pad",
    "waveformOscType": "PWM Square",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "Low",
    "attack": "Slow",
    "decay": "Max",
    "sustain": "Max",
    "release": "Slow",
    "chorus": "Chorus 1",
    "delayReverb": "Reverb 4",
    "notesDescription": "Glassy Digital Pad: (Bell-like texture)"
  },
  {
    "bankPatch": "3-8",
    "soundNameCategory": "Aggressive Sync Lead",
    "waveformOscType": "Sync Saw",
    "filterFreq": "High",
    "resonance": "Mid",
    "envMod": "Mid",
    "attack": "Fast",
    "decay": "Max",
    "sustain": "Max",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Delay 2",
    "notesDescription": "Aggressive Sync Lead: (Hard rock edge)"
  },
  {
    "bankPatch": "4-1",
    "soundNameCategory": "Metallic Bell Pluck",
    "waveformOscType": "Cross-Mod",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "Mid",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "Low",
    "release": "Mid",
    "chorus": "Off",
    "delayReverb": "Reverb 3",
    "notesDescription": "Metallic Bell Pluck: (FM character)"
  },
  {
    "bankPatch": "4-2",
    "soundNameCategory": "Velo-Sensitive Clav Keys",
    "waveformOscType": "Square",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "High",
    "attack": "Fast",
    "decay": "Fast",
    "sustain": "Low",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Reverb 1",
    "notesDescription": "Velo-Sensitive Clav Keys"
  },
  {
    "bankPatch": "4-3",
    "soundNameCategory": "Warm Strings Pad",
    "waveformOscType": "Saw",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "Off",
    "attack": "Mid",
    "decay": "Max",
    "sustain": "Max",
    "release": "Mid",
    "chorus": "Chorus 1",
    "delayReverb": "Reverb 2",
    "notesDescription": "Warm Strings Pad: (Classic analog ensemble)"
  },
  {
    "bankPatch": "4-4",
    "soundNameCategory": "Drive Bass",
    "waveformOscType": "Saw + Sub",
    "filterFreq": "Low",
    "resonance": "Low",
    "envMod": "Low",
    "attack": "Fast",
    "decay": "Max",
    "sustain": "Max",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Off",
    "notesDescription": "Drive Bass: (Slightly saturated feel)"
  },
  {
    "bankPatch": "4-5",
    "soundNameCategory": "Bright Swell Pad",
    "waveformOscType": "Super Saw",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "High",
    "attack": "Slow",
    "decay": "Max",
    "sustain": "Max",
    "release": "Mid",
    "chorus": "Chorus 2",
    "delayReverb": "Reverb 4",
    "notesDescription": "Bright Swell Pad: (Trance/Modern style)"
  },
  {
    "bankPatch": "4-6",
    "soundNameCategory": "Expressive Solo Lead",
    "waveformOscType": "Saw",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "Off",
    "attack": "Fast",
    "decay": "Max",
    "sustain": "Max",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Delay 3",
    "notesDescription": "Expressive Solo Lead: (Vibrato friendly)"
  },
  {
    "bankPatch": "4-7",
    "soundNameCategory": "Resonant Moving Texture",
    "waveformOscType": "Saw",
    "filterFreq": "Low",
    "resonance": "High",
    "envMod": "Slow LFO",
    "attack": "Slow",
    "decay": "Max",
    "sustain": "Max",
    "release": "Slow",
    "chorus": "Off",
    "delayReverb": "Reverb 3",
    "notesDescription": "Resonant Moving Texture"
  },
  {
    "bankPatch": "4-8",
    "soundNameCategory": "Classic 90s Organ",
    "waveformOscType": "Multi-Sine",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "Off",
    "attack": "Fast",
    "decay": "Fast",
    "sustain": "Max",
    "release": "Fast",
    "chorus": "Chorus 1",
    "delayReverb": "Reverb 1",
    "notesDescription": "Classic 90s Organ: (Deep house style)"
  },
  {
    "bankPatch": "5-1",
    "soundNameCategory": "Damped Wood Block Pluck",
    "waveformOscType": "Square",
    "filterFreq": "Low",
    "resonance": "Low",
    "envMod": "Fast",
    "attack": "Fast",
    "decay": "Fast",
    "sustain": "Off",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Delay 1",
    "notesDescription": "Damped Wood Block Pluck"
  },
  {
    "bankPatch": "5-2",
    "soundNameCategory": "Detuned Pop Piano Keys",
    "waveformOscType": "Unison Saw",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "Low",
    "attack": "Fast",
    "decay": "Max",
    "sustain": "Mid",
    "release": "Mid",
    "chorus": "Chorus 1",
    "delayReverb": "Reverb 2",
    "notesDescription": "Detuned Pop Piano Keys"
  },
  {
    "bankPatch": "5-3",
    "soundNameCategory": "Rich Warm Brass",
    "waveformOscType": "Saw + Square",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "Mid",
    "attack": "Mid",
    "decay": "Max",
    "sustain": "Max",
    "release": "Mid",
    "chorus": "Chorus 1",
    "delayReverb": "Reverb 2",
    "notesDescription": "Rich Warm Brass: (Polysynth brass)"
  },
  {
    "bankPatch": "5-4",
    "soundNameCategory": "Sub Punch Bass",
    "waveformOscType": "Sine + Sub",
    "filterFreq": "Low",
    "resonance": "Low",
    "envMod": "Fast",
    "attack": "Fast",
    "decay": "Fast",
    "sustain": "Max",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Off",
    "notesDescription": "Sub Punch Bass: (Hip Hop/RnB sub)"
  },
  {
    "bankPatch": "5-5",
    "soundNameCategory": "Airy Flute Pad",
    "waveformOscType": "Triangle + Noise",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "Low",
    "attack": "Slow",
    "decay": "Max",
    "sustain": "Max",
    "release": "Mid",
    "chorus": "Off",
    "delayReverb": "Reverb 4",
    "notesDescription": "Airy Flute Pad: (Breath-like opening)"
  },
  {
    "bankPatch": "5-6",
    "soundNameCategory": "Glitchy S&H Lead",
    "waveformOscType": "Square",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "S&H LFO",
    "attack": "Fast",
    "decay": "Max",
    "sustain": "Max",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Delay 3",
    "notesDescription": "Glitchy S&H Lead"
  },
  {
    "bankPatch": "5-7",
    "soundNameCategory": "Deep Cosmic Swell",
    "waveformOscType": "Saw",
    "filterFreq": "Low",
    "resonance": "Low",
    "envMod": "Slow LFO",
    "attack": "Slow",
    "decay": "Max",
    "sustain": "Max",
    "release": "Slow",
    "chorus": "Chorus 2",
    "delayReverb": "Reverb 4",
    "notesDescription": "Deep Cosmic Swell: (Sci-Fi soundtrack texture)"
  },
  {
    "bankPatch": "5-8",
    "soundNameCategory": "Hard Detuned Rave Stabs",
    "waveformOscType": "Super Saw",
    "filterFreq": "High",
    "resonance": "Mid",
    "envMod": "High",
    "attack": "Fast",
    "decay": "Fast",
    "sustain": "Max",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Delay 2",
    "notesDescription": "Hard Detuned Rave Stabs: (90s rave/techno)"
  },
  {
    "bankPatch": "6-1",
    "soundNameCategory": "Crisp Acoustic-Like Pluck",
    "waveformOscType": "Short Saw",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "High",
    "attack": "Fast",
    "decay": "Fast",
    "sustain": "Off",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Delay 2",
    "notesDescription": "Crisp Acoustic-Like Pluck: (Guitar/Harp vibe)"
  },
  {
    "bankPatch": "6-2",
    "soundNameCategory": "Electric Rhodes Piano Keys",
    "waveformOscType": "Sine + Triangle",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "Low",
    "attack": "Fast",
    "decay": "Max",
    "sustain": "Mid",
    "release": "Mid",
    "chorus": "Chorus 1",
    "delayReverb": "Reverb 2",
    "notesDescription": "Electric Rhodes Piano Keys"
  },
  {
    "bankPatch": "6-3",
    "soundNameCategory": "Mellow Warm Horns",
    "waveformOscType": "Saw",
    "filterFreq": "Low",
    "resonance": "Low",
    "envMod": "Mid",
    "attack": "Mid",
    "decay": "Max",
    "sustain": "Max",
    "release": "Mid",
    "chorus": "Chorus 1",
    "delayReverb": "Reverb 1",
    "notesDescription": "Mellow Warm Horns"
  },
  {
    "bankPatch": "6-4",
    "soundNameCategory": "Clicky Attack Bass",
    "waveformOscType": "Saw + Sub",
    "filterFreq": "Low",
    "resonance": "Low",
    "envMod": "Fast",
    "attack": "Fast",
    "decay": "Fast",
    "sustain": "Max",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Off",
    "notesDescription": "Clicky Attack Bass: (Transient heavy)"
  },
  {
    "bankPatch": "6-5",
    "soundNameCategory": "Shimmering High Pad",
    "waveformOscType": "Super Saw",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "Low",
    "attack": "Slow",
    "decay": "Max",
    "sustain": "Max",
    "release": "Max",
    "chorus": "Chorus 2",
    "delayReverb": "Reverb 4",
    "notesDescription": "Shimmering High Pad: (Ethereal high end)"
  },
  {
    "bankPatch": "6-6",
    "soundNameCategory": "Searing Sync Lead",
    "waveformOscType": "Sync Saw",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "High",
    "attack": "Fast",
    "decay": "Max",
    "sustain": "Max",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Delay 3",
    "notesDescription": "Searing Sync Lead"
  },
  {
    "bankPatch": "6-7",
    "soundNameCategory": "Warm Low End Drone",
    "waveformOscType": "Square + Sub",
    "filterFreq": "Low",
    "resonance": "Low",
    "envMod": "Off",
    "attack": "Slow",
    "decay": "Max",
    "sustain": "Max",
    "release": "Slow",
    "chorus": "Chorus 1",
    "delayReverb": "Reverb 3",
    "notesDescription": "Warm Low End Drone"
  },
  {
    "bankPatch": "6-8",
    "soundNameCategory": "Hyper Pop Lead",
    "waveformOscType": "Super Saw + Square",
    "filterFreq": "High",
    "resonance": "Mid",
    "envMod": "Low",
    "attack": "Fast",
    "decay": "Max",
    "sustain": "Max",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Delay 2",
    "notesDescription": "Hyper Pop Lead: (Bright, modern cutting tone)"
  },
  {
    "bankPatch": "7-1",
    "soundNameCategory": "Percolating Modular Pluck",
    "waveformOscType": "Square",
    "filterFreq": "Low",
    "resonance": "Mid",
    "envMod": "High",
    "attack": "Fast",
    "decay": "Fast",
    "sustain": "Off",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Delay 3",
    "notesDescription": "Percolating Modular Pluck: (Rhythmic sequence friendly)"
  },
  {
    "bankPatch": "7-2",
    "soundNameCategory": "FM Electric Piano Keys",
    "waveformOscType": "Cross-Mod Sine",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "Mid",
    "attack": "Fast",
    "decay": "Max",
    "sustain": "Mid",
    "release": "Mid",
    "chorus": "Chorus 1",
    "delayReverb": "Reverb 2",
    "notesDescription": "FM Electric Piano Keys: (DX7 style)"
  },
  {
    "bankPatch": "7-3",
    "soundNameCategory": "Stately Synth Brass",
    "waveformOscType": "Saw",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "Mid",
    "attack": "Mid",
    "decay": "Max",
    "sustain": "Max",
    "release": "Mid",
    "chorus": "Off",
    "delayReverb": "Reverb 2",
    "notesDescription": "Stately Synth Brass"
  },
  {
    "bankPatch": "7-4",
    "soundNameCategory": "Fuzz/Overdriven Bass",
    "waveformOscType": "Sync Saw",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "Low",
    "attack": "Fast",
    "decay": "Max",
    "sustain": "Max",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Off",
    "notesDescription": "Fuzz/Overdriven Bass"
  },
  {
    "bankPatch": "7-5",
    "soundNameCategory": "Slow Vibrato Pad",
    "waveformOscType": "Saw",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "Vibrato LFO",
    "attack": "Slow",
    "decay": "Max",
    "sustain": "Max",
    "release": "Mid",
    "chorus": "Chorus 1",
    "delayReverb": "Reverb 3",
    "notesDescription": "Slow Vibrato Pad: (Vintage tape warble feel)"
  },
  {
    "bankPatch": "7-6",
    "soundNameCategory": "Theremin-Like Whistle Lead",
    "waveformOscType": "Sine",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "Off",
    "attack": "Mid",
    "decay": "Max",
    "sustain": "Max",
    "release": "Mid",
    "chorus": "Off",
    "delayReverb": "Delay 3",
    "notesDescription": "Theremin-Like Whistle Lead: (Portamento friendly)"
  },
  {
    "bankPatch": "7-7",
    "soundNameCategory": "Warm Hollow Pad",
    "waveformOscType": "Square",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "Off",
    "attack": "Slow",
    "decay": "Max",
    "sustain": "Max",
    "release": "Slow",
    "chorus": "Chorus 1",
    "delayReverb": "Reverb 4",
    "notesDescription": "Warm Hollow Pad"
  },
  {
    "bankPatch": "7-8",
    "soundNameCategory": "Aggressive Saw Lead",
    "waveformOscType": "Unison Saw",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "Low",
    "attack": "Fast",
    "decay": "Max",
    "sustain": "Max",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Delay 1",
    "notesDescription": "Aggressive Saw Lead"
  },
  {
    "bankPatch": "8-1",
    "soundNameCategory": "Lo-Fi Vinyl Crackle Pluck",
    "waveformOscType": "Saw + Noise",
    "filterFreq": "Low",
    "resonance": "Low",
    "envMod": "Mid",
    "attack": "Fast",
    "decay": "Fast",
    "sustain": "Off",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Reverb 1",
    "notesDescription": "Lo-Fi Vinyl Crackle Pluck: (Grit texture)"
  },
  {
    "bankPatch": "8-2",
    "soundNameCategory": "Detuned Wurlitzer Keys",
    "waveformOscType": "Square + Triangle",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "Low",
    "attack": "Fast",
    "decay": "Max",
    "sustain": "Mid",
    "release": "Mid",
    "chorus": "Chorus 1",
    "delayReverb": "Reverb 2",
    "notesDescription": "Detuned Wurlitzer Keys"
  },
  {
    "bankPatch": "8-3",
    "soundNameCategory": "Bright Filter Sweep Brass",
    "waveformOscType": "Super Saw",
    "filterFreq": "Low",
    "resonance": "Mid",
    "envMod": "High",
    "attack": "Mid",
    "decay": "Mid",
    "sustain": "Max",
    "release": "Mid",
    "chorus": "Off",
    "delayReverb": "Reverb 2",
    "notesDescription": "Bright Filter Sweep Brass"
  },
  {
    "bankPatch": "8-4",
    "soundNameCategory": "Gated Rhythmic Bass",
    "waveformOscType": "Square",
    "filterFreq": "Low",
    "resonance": "Low",
    "envMod": "Gated LFO",
    "attack": "Fast",
    "decay": "Max",
    "sustain": "Max",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Off",
    "notesDescription": "Gated Rhythmic Bass"
  },
  {
    "bankPatch": "8-5",
    "soundNameCategory": "Bright Evolving String Pad",
    "waveformOscType": "Unison Saw",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "Slow LFO",
    "attack": "Slow",
    "decay": "Max",
    "sustain": "Max",
    "release": "Max",
    "chorus": "Chorus 2",
    "delayReverb": "Reverb 3",
    "notesDescription": "Bright Evolving String Pad"
  },
  {
    "bankPatch": "8-6",
    "soundNameCategory": "Soaring Square Lead",
    "waveformOscType": "Square",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "Off",
    "attack": "Fast",
    "decay": "Max",
    "sustain": "Max",
    "release": "Fast",
    "chorus": "Chorus 1",
    "delayReverb": "Delay 2",
    "notesDescription": "Soaring Square Lead"
  },
  {
    "bankPatch": "8-7",
    "soundNameCategory": "Deep Submerged Pad",
    "waveformOscType": "Sine",
    "filterFreq": "Low",
    "resonance": "Low",
    "envMod": "Off",
    "attack": "Slow",
    "decay": "Max",
    "sustain": "Max",
    "release": "Slow",
    "chorus": "Off",
    "delayReverb": "Reverb 4",
    "notesDescription": "Deep Submerged Pad: (Underwater/muffled tone)"
  },
  {
    "bankPatch": "8-8",
    "soundNameCategory": "Aggressive Screamer Lead",
    "waveformOscType": "Cross-Mod Saw",
    "filterFreq": "High",
    "resonance": "High",
    "envMod": "High",
    "attack": "Fast",
    "decay": "Max",
    "sustain": "Max",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Delay 3",
    "notesDescription": "Aggressive Screamer Lead: (Industrial/Noise style)"
  }
]