export const presetsData = [
  {
    "blank": "",
    "preset": "1 - 1",
    "glide": "x",
    "octave": "0",
    "rate": "x",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "x",
    "saw": "SAW",
    "sub": "50%",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Mid",
    "env": "+ Low",
    "lfo_2": "x",
    "kybd": "x",
    "env_gate": "Env",
    "a": "None",
    "d": "Mid",
    "s_control_range": "Mid (Low -> High)",
    "r": "Fast",
    "blank_3": "I",
    "notes_description": "Mellow Sub Octave Pluck: Mild Sustain once Envelope control is past 50% (Good for Deadmaus5)",
    "bankPatch": "1-1",
    "soundNameCategory": "Mellow Sub Octave Pluck",
    "notesDescription": "Mellow Sub Octave Pluck: Mild Sustain once Envelope control is past 50% (Good for Deadmaus5)",
    "waveformOscType": "Saw + Sub 50%",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "+ Low",
    "attack": "None",
    "decay": "Mid",
    "sustain": "Mid (Low -> High)",
    "release": "Fast",
    "chorus": "I",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "1 - 2",
    "glide": "x",
    "octave": "0",
    "rate": "x",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "SQU",
    "saw": "x",
    "sub": "x",
    "noise": "x",
    "blank_2": "Y",
    "freq": "Mid",
    "res": "Mid",
    "env": "+ Low",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Mid",
    "s_control_range": "Low (Low -> Mid)",
    "r": "None",
    "blank_3": "Off",
    "notes_description": "Square Pluck:",
    "bankPatch": "1-2",
    "soundNameCategory": "Square Pluck",
    "notesDescription": "Square Pluck:",
    "waveformOscType": "Square",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "+ Low",
    "attack": "None",
    "decay": "Mid",
    "sustain": "Low (Low -> Mid)",
    "release": "None",
    "chorus": "Off",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "1 - 3",
    "glide": "x",
    "octave": "0",
    "rate": "x",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "SQU",
    "saw": "x",
    "sub": "x",
    "noise": "x",
    "blank_2": "Y",
    "freq": "Mid",
    "res": "Mid",
    "env": "+ Low",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Mid",
    "s_control_range": "Off (Off -> High)",
    "r": "Mid",
    "blank_3": "Off",
    "notes_description": "Mellow Mallet: Sustains once Envelope control is past 50%",
    "bankPatch": "1-3",
    "soundNameCategory": "Mellow Mallet",
    "notesDescription": "Mellow Mallet: Sustains once Envelope control is past 50%",
    "waveformOscType": "Square",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "+ Low",
    "attack": "None",
    "decay": "Mid",
    "sustain": "Off (Off -> High)",
    "release": "Mid",
    "chorus": "Off",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "1 - 4",
    "glide": "x",
    "octave": "0",
    "rate": "Slow",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "SQU",
    "saw": "x",
    "sub": "x",
    "noise": "High",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Mid",
    "env": "x",
    "lfo_2": "Low",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Mid",
    "s_control_range": "Off (Off -> High)",
    "r": "Mid",
    "blank_3": "Off",
    "notes_description": "Noisy Mellow Pluck: Sustains once Envelope control is past 50%",
    "bankPatch": "1-4",
    "soundNameCategory": "Noisy Mellow Pluck",
    "notesDescription": "Noisy Mellow Pluck: Sustains once Envelope control is past 50%",
    "waveformOscType": "Square",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "x",
    "attack": "None",
    "decay": "Mid",
    "sustain": "Off (Off -> High)",
    "release": "Mid",
    "chorus": "Off",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "1 - 5",
    "glide": "x",
    "octave": "+1",
    "rate": "x",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "x",
    "saw": "SAW",
    "sub": "100%",
    "noise": "Mid",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Mid",
    "env": "+ Low",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Mid",
    "s_control_range": "Off (Off -> High)",
    "r": "Mid",
    "blank_3": "I",
    "notes_description": "Noisy Octave Pluck: Sustains once Envelope control is past 50%",
    "bankPatch": "1-5",
    "soundNameCategory": "Noisy Octave Pluck",
    "notesDescription": "Noisy Octave Pluck: Sustains once Envelope control is past 50%",
    "waveformOscType": "Saw + Sub 100%",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "+ Low",
    "attack": "None",
    "decay": "Mid",
    "sustain": "Off (Off -> High)",
    "release": "Mid",
    "chorus": "I",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "1 - 6",
    "glide": "x",
    "octave": "+1",
    "rate": "Mid",
    "delay": "Y",
    "lfo": "x",
    "pwm": "LFO",
    "pulse": "PWM",
    "saw": "x",
    "sub": "100%",
    "noise": "Mid",
    "blank_2": "x",
    "freq": "High",
    "res": "Mid",
    "env": "+ Mid",
    "lfo_2": "Mid",
    "kybd": "x",
    "env_gate": "Env",
    "a": "None",
    "d": "Mid",
    "s_control_range": "Off (Off -> High)",
    "r": "None",
    "blank_3": "Off",
    "notes_description": "Harpsichord: Sustains + PWM once Envelope control is past 50%",
    "bankPatch": "1-6",
    "soundNameCategory": "Harpsichord",
    "notesDescription": "Harpsichord: Sustains + PWM once Envelope control is past 50%",
    "waveformOscType": "Sub 100% + LFO + PWM",
    "filterFreq": "High",
    "resonance": "Mid",
    "envMod": "+ Mid",
    "attack": "None",
    "decay": "Mid",
    "sustain": "Off (Off -> High)",
    "release": "None",
    "chorus": "Off",
    "delayReverb": "Y"
  },
  {
    "blank": "",
    "preset": "1 - 7",
    "glide": "x",
    "octave": "0",
    "rate": "x",
    "delay": "x",
    "lfo": "x",
    "pwm": "Fixed",
    "pulse": "15%",
    "saw": "x",
    "sub": "x",
    "noise": "x",
    "blank_2": "x",
    "freq": "Low",
    "res": "Low",
    "env": "+ High",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Mid",
    "s_control_range": "Off (Off -> High)",
    "r": "None",
    "blank_3": "I",
    "notes_description": "Chorus Clavinet: Sustains once Envelope control is past 50%",
    "bankPatch": "1-7",
    "soundNameCategory": "Chorus Clavinet",
    "notesDescription": "Chorus Clavinet: Sustains once Envelope control is past 50%",
    "waveformOscType": "Fixed + Sub 15%",
    "filterFreq": "Low",
    "resonance": "Low",
    "envMod": "+ High",
    "attack": "None",
    "decay": "Mid",
    "sustain": "Off (Off -> High)",
    "release": "None",
    "chorus": "I",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "1 - 8",
    "glide": "x",
    "octave": "+1",
    "rate": "x",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "SQU",
    "saw": "x",
    "sub": "100%",
    "noise": "x",
    "blank_2": "x",
    "freq": "Low",
    "res": "Low",
    "env": "+ High",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Mid",
    "s_control_range": "Off (Off -> High)",
    "r": "Mid",
    "blank_3": "I",
    "notes_description": "Chorus Harp: Mild Sustain once Envelope control is past 50%",
    "bankPatch": "1-8",
    "soundNameCategory": "Chorus Harp",
    "notesDescription": "Chorus Harp: Mild Sustain once Envelope control is past 50%",
    "waveformOscType": "Sub 100% + Square",
    "filterFreq": "Low",
    "resonance": "Low",
    "envMod": "+ High",
    "attack": "None",
    "decay": "Mid",
    "sustain": "Off (Off -> High)",
    "release": "Mid",
    "chorus": "I",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "2 - 1",
    "glide": "x",
    "octave": "+1",
    "rate": "1/8th",
    "delay": "x",
    "lfo": "x",
    "pwm": "LFO*",
    "pulse": "PWM",
    "saw": "x",
    "sub": "100%",
    "noise": "Low",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Mid",
    "env": "x",
    "lfo_2": "Low*",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Mid",
    "s_control_range": "Off (Off -> High)",
    "r": "Fast",
    "blank_3": "II",
    "notes_description": "Staccato Steel Drum: LFO retriggers at 1/8th notes in a SAW wave once Envelope Control is past 50%",
    "bankPatch": "2-1",
    "soundNameCategory": "Staccato Steel Drum",
    "notesDescription": "Staccato Steel Drum: LFO retriggers at 1/8th notes in a SAW wave once Envelope Control is past 50%",
    "waveformOscType": "Sub 100% + LFO + PWM",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "x",
    "attack": "None",
    "decay": "Mid",
    "sustain": "Off (Off -> High)",
    "release": "Fast",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "2 - 2",
    "glide": "x",
    "octave": "0",
    "rate": "x",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "x",
    "saw": "SAW",
    "sub": "x",
    "noise": "x",
    "blank_2": "Y",
    "freq": "Low",
    "res": "Mid",
    "env": "+ High",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Mid",
    "s_control_range": "Off (Off -> High)",
    "r": "Fast",
    "blank_3": "II",
    "notes_description": "Bright Detuned Saw Pluck: Sustains once Envelope control is past 50% (Increase Attack for Brass Ensemble Stab)",
    "bankPatch": "2-2",
    "soundNameCategory": "Bright Detuned Saw Pluck",
    "notesDescription": "Bright Detuned Saw Pluck: Sustains once Envelope control is past 50% (Increase Attack for Brass Ensemble Stab)",
    "waveformOscType": "Saw",
    "filterFreq": "Low",
    "resonance": "Mid",
    "envMod": "+ High",
    "attack": "None",
    "decay": "Mid",
    "sustain": "Off (Off -> High)",
    "release": "Fast",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "2 - 3",
    "glide": "x",
    "octave": "+1",
    "rate": "x",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "x",
    "saw": "SAW",
    "sub": "100%",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Mid",
    "env": "+ High",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Mid",
    "s_control_range": "Off (Off -> High)",
    "r": "Mid",
    "blank_3": "I",
    "notes_description": "Synthy 80s Clean Guitar: Sustains once Envelope control is past 50%",
    "bankPatch": "2-3",
    "soundNameCategory": "Synthy 80s Clean Guitar",
    "notesDescription": "Synthy 80s Clean Guitar: Sustains once Envelope control is past 50%",
    "waveformOscType": "Saw + Sub 100%",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "+ High",
    "attack": "None",
    "decay": "Mid",
    "sustain": "Off (Off -> High)",
    "release": "Mid",
    "chorus": "I",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "2 - 4",
    "glide": "Fast",
    "octave": "+1",
    "rate": "Mid",
    "delay": "x",
    "lfo": "x",
    "pwm": "LFO",
    "pulse": "PWM",
    "saw": "x",
    "sub": "100%",
    "noise": "Mid",
    "blank_2": "x",
    "freq": "Mid",
    "res": "High",
    "env": "+ Low",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Fast",
    "d": "Mid",
    "s_control_range": "Off (Off -> High)",
    "r": "None",
    "blank_3": "II",
    "notes_description": "Gliding Noisy Pluck: Sustains once Envelope control is past 50%",
    "bankPatch": "2-4",
    "soundNameCategory": "Gliding Noisy Pluck",
    "notesDescription": "Gliding Noisy Pluck: Sustains once Envelope control is past 50%",
    "waveformOscType": "Sub 100% + LFO + PWM",
    "filterFreq": "Mid",
    "resonance": "High",
    "envMod": "+ Low",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "Off (Off -> High)",
    "release": "None",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "2 - 5",
    "glide": "x",
    "octave": "0",
    "rate": "x",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "SQU",
    "saw": "SAW",
    "sub": "x",
    "noise": "Mid",
    "blank_2": "x",
    "freq": "Mid",
    "res": "High",
    "env": "+ Low",
    "lfo_2": "x",
    "kybd": "x",
    "env_gate": "Env",
    "a": "Fast",
    "d": "Mid",
    "s_control_range": "Off (Off -> Mid)",
    "r": "Fast",
    "blank_3": "II",
    "notes_description": "Octave Splash: Mild Sustain once Envelope control is past 50%",
    "bankPatch": "2-5",
    "soundNameCategory": "Octave Splash",
    "notesDescription": "Octave Splash: Mild Sustain once Envelope control is past 50%",
    "waveformOscType": "Saw + Square",
    "filterFreq": "Mid",
    "resonance": "High",
    "envMod": "+ Low",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "Off (Off -> Mid)",
    "release": "Fast",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "2 - 6",
    "glide": "Fast",
    "octave": "0",
    "rate": "Mid",
    "delay": "x",
    "lfo": "x",
    "pwm": "Fixed",
    "pulse": "33%",
    "saw": "x",
    "sub": "x",
    "noise": "Mid",
    "blank_2": "Y",
    "freq": "Mid",
    "res": "High",
    "env": "+ Mid",
    "lfo_2": "Mid",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Fast",
    "s_control_range": "High",
    "r": "Mid",
    "blank_3": "I",
    "notes_description": "Plectrum Wind:",
    "bankPatch": "2-6",
    "soundNameCategory": "Plectrum Wind",
    "notesDescription": "Plectrum Wind:",
    "waveformOscType": "Fixed + Sub 33%",
    "filterFreq": "Mid",
    "resonance": "High",
    "envMod": "+ Mid",
    "attack": "None",
    "decay": "Fast",
    "sustain": "High",
    "release": "Mid",
    "chorus": "I",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "2 - 7",
    "glide": "x",
    "octave": "+1",
    "rate": "Mid",
    "delay": "Y",
    "lfo": "x",
    "pwm": "Fixed",
    "pulse": "33%",
    "saw": "x",
    "sub": "100%",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Low",
    "env": "+ Low",
    "lfo_2": "Low",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Fast",
    "s_control_range": "Mid (Low -> High)",
    "r": "Fast",
    "blank_3": "II",
    "notes_description": "Plectrum Mellotron Chorus:",
    "bankPatch": "2-7",
    "soundNameCategory": "Plectrum Mellotron Chorus",
    "notesDescription": "Plectrum Mellotron Chorus:",
    "waveformOscType": "Sub 100% + Fixed + Sub 33%",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "+ Low",
    "attack": "None",
    "decay": "Fast",
    "sustain": "Mid (Low -> High)",
    "release": "Fast",
    "chorus": "II",
    "delayReverb": "Y"
  },
  {
    "blank": "",
    "preset": "2 - 8",
    "glide": "x",
    "octave": "0",
    "rate": "Fast",
    "delay": "Y",
    "lfo": "x",
    "pwm": "Fixed",
    "pulse": "33%",
    "saw": "x",
    "sub": "x",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Low",
    "env": "+ Low",
    "lfo_2": "Mid",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Fast",
    "s_control_range": "High (Mid -> High)",
    "r": "Slow",
    "blank_3": "I",
    "notes_description": "Air Harp:",
    "bankPatch": "2-8",
    "soundNameCategory": "Air Harp",
    "notesDescription": "Air Harp:",
    "waveformOscType": "Fixed + Sub 33%",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "+ Low",
    "attack": "None",
    "decay": "Fast",
    "sustain": "High (Mid -> High)",
    "release": "Slow",
    "chorus": "I",
    "delayReverb": "Y"
  },
  {
    "blank": "",
    "preset": "3 - 1",
    "glide": "x",
    "octave": "0",
    "rate": "x",
    "delay": "x",
    "lfo": "x",
    "pwm": "Fixed",
    "pulse": "25%",
    "saw": "x",
    "sub": "x",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Low",
    "env": "x",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Slow",
    "s_control_range": "Low (Low -> High)",
    "r": "Slow",
    "blank_3": "I",
    "notes_description": "Ambient Piano:",
    "bankPatch": "3-1",
    "soundNameCategory": "Ambient Piano",
    "notesDescription": "Ambient Piano:",
    "waveformOscType": "Fixed + Sub 25%",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "x",
    "attack": "None",
    "decay": "Slow",
    "sustain": "Low (Low -> High)",
    "release": "Slow",
    "chorus": "I",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "3 - 2",
    "glide": "x",
    "octave": "0",
    "rate": "x",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "SQU",
    "saw": "x",
    "sub": "x",
    "noise": "x",
    "blank_2": "Y",
    "freq": "Mid",
    "res": "High",
    "env": "+ Low",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Fast",
    "s_control_range": "Mid (Low -> High)",
    "r": "Mid",
    "blank_3": "Off",
    "notes_description": "Synth Vibraphone:",
    "bankPatch": "3-2",
    "soundNameCategory": "Synth Vibraphone",
    "notesDescription": "Synth Vibraphone:",
    "waveformOscType": "Square",
    "filterFreq": "Mid",
    "resonance": "High",
    "envMod": "+ Low",
    "attack": "None",
    "decay": "Fast",
    "sustain": "Mid (Low -> High)",
    "release": "Mid",
    "chorus": "Off",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "3 - 3",
    "glide": "x",
    "octave": "+1",
    "rate": "x",
    "delay": "x",
    "lfo": "x",
    "pwm": "Fixed",
    "pulse": "25%",
    "saw": "x",
    "sub": "100%",
    "noise": "x",
    "blank_2": "Y",
    "freq": "Mid",
    "res": "Mid",
    "env": "+ Mid",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Mid",
    "s_control_range": "Mid (Low -> High)",
    "r": "Mid",
    "blank_3": "II",
    "notes_description": "Hammered Dulcimar:",
    "bankPatch": "3-3",
    "soundNameCategory": "Hammered Dulcimar",
    "notesDescription": "Hammered Dulcimar:",
    "waveformOscType": "Sub 100% + Fixed + Sub 25%",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "+ Mid",
    "attack": "None",
    "decay": "Mid",
    "sustain": "Mid (Low -> High)",
    "release": "Mid",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "3 - 4",
    "glide": "x",
    "octave": "0",
    "rate": "x",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "x",
    "saw": "SAW",
    "sub": "x",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Low",
    "env": "+ Low",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Mid",
    "s_control_range": "Mid (Low -> High)",
    "r": "Mid",
    "blank_3": "I",
    "notes_description": "Saw Piano:",
    "bankPatch": "3-4",
    "soundNameCategory": "Saw Piano",
    "notesDescription": "Saw Piano:",
    "waveformOscType": "Saw",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "+ Low",
    "attack": "None",
    "decay": "Mid",
    "sustain": "Mid (Low -> High)",
    "release": "Mid",
    "chorus": "I",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "3 - 5",
    "glide": "x",
    "octave": "0",
    "rate": "x",
    "delay": "x",
    "lfo": "x",
    "pwm": "Env",
    "pulse": "PWM",
    "saw": "x",
    "sub": "x",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Mid",
    "env": "+ Mid",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env/Gate",
    "a": "Fast",
    "d": "Mid",
    "s_control_range": "Mid (Low -> High)",
    "r": "None",
    "blank_3": "I",
    "notes_description": "Brass Pluck: VCA Gate for low Envelope settings, VCA Env for high Envelope settings (Attack only)",
    "bankPatch": "3-5",
    "soundNameCategory": "Brass Pluck",
    "notesDescription": "Brass Pluck: VCA Gate for low Envelope settings, VCA Env for high Envelope settings (Attack only)",
    "waveformOscType": "Env + PWM",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "+ Mid",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "Mid (Low -> High)",
    "release": "None",
    "chorus": "I",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "3 - 6",
    "glide": "x",
    "octave": "+1",
    "rate": "Slow",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "SQU",
    "saw": "x",
    "sub": "100%",
    "noise": "x",
    "blank_2": "Y",
    "freq": "Mid",
    "res": "Mid",
    "env": "+ High",
    "lfo_2": "Mid",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Mid",
    "d": "Mid",
    "s_control_range": "High (Mid -> High)",
    "r": "Mid",
    "blank_3": "I",
    "notes_description": "Resonant Blown Glass:",
    "bankPatch": "3-6",
    "soundNameCategory": "Resonant Blown Glass",
    "notesDescription": "Resonant Blown Glass:",
    "waveformOscType": "Sub 100% + Square",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "+ High",
    "attack": "Mid",
    "decay": "Mid",
    "sustain": "High (Mid -> High)",
    "release": "Mid",
    "chorus": "I",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "3 - 7",
    "glide": "x",
    "octave": "0",
    "rate": "x",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "x",
    "saw": "SAW",
    "sub": "x",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Mid",
    "env": "+ Mid",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Fast",
    "d": "Fast",
    "s_control_range": "Mid (Mid -> High)",
    "r": "Fast",
    "blank_3": "Off",
    "notes_description": "Acid Saw: (Turn Attack to 0% for pure Saw Pluck)",
    "bankPatch": "3-7",
    "soundNameCategory": "Acid Saw",
    "notesDescription": "Acid Saw: (Turn Attack to 0% for pure Saw Pluck)",
    "waveformOscType": "Saw",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "+ Mid",
    "attack": "Fast",
    "decay": "Fast",
    "sustain": "Mid (Mid -> High)",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "3 - 8",
    "glide": "x",
    "octave": "0",
    "rate": "Mid",
    "delay": "Y",
    "lfo": "Low",
    "pwm": "x",
    "pulse": "x",
    "saw": "SAW",
    "sub": "x",
    "noise": "x",
    "blank_2": "x",
    "freq": "Low",
    "res": "Low",
    "env": "+ High",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Fast",
    "d": "Fast",
    "s_control_range": "Mid (Mid -> High)",
    "r": "Fast",
    "blank_3": "Off",
    "notes_description": "Bright Trumpet: (Turn Attack to 0% for Plectrum Bass Guitar)",
    "bankPatch": "3-8",
    "soundNameCategory": "Bright Trumpet",
    "notesDescription": "Bright Trumpet: (Turn Attack to 0% for Plectrum Bass Guitar)",
    "waveformOscType": "Saw + Low",
    "filterFreq": "Low",
    "resonance": "Low",
    "envMod": "+ High",
    "attack": "Fast",
    "decay": "Fast",
    "sustain": "Mid (Mid -> High)",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Y"
  },
  {
    "blank": "",
    "preset": "4 - 1",
    "glide": "x",
    "octave": "+1",
    "rate": "Mid",
    "delay": "x",
    "lfo": "x",
    "pwm": "LFO",
    "pulse": "PWM",
    "saw": "x",
    "sub": "100%",
    "noise": "x",
    "blank_2": "x",
    "freq": "High",
    "res": "Low",
    "env": "+ High",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Fast",
    "d": "Mid",
    "s_control_range": "High (Mid -> High)",
    "r": "None",
    "blank_3": "II",
    "notes_description": "Octave PWM Lead:",
    "bankPatch": "4-1",
    "soundNameCategory": "Octave PWM Lead",
    "notesDescription": "Octave PWM Lead:",
    "waveformOscType": "Sub 100% + LFO + PWM",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "+ High",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "High (Mid -> High)",
    "release": "None",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "4 - 2",
    "glide": "Fast",
    "octave": "0",
    "rate": "Mid",
    "delay": "x",
    "lfo": "x",
    "pwm": "Fixed",
    "pulse": "25%",
    "saw": "x",
    "sub": "x",
    "noise": "x",
    "blank_2": "x",
    "freq": "High",
    "res": "High",
    "env": "x",
    "lfo_2": "High",
    "kybd": "x",
    "env_gate": "Env",
    "a": "None",
    "d": "Fast",
    "s_control_range": "High",
    "r": "None",
    "blank_3": "I",
    "notes_description": "Gliding Pulse Lead I: Wide LFO Filter Sweep for low Filter/Envelope values",
    "bankPatch": "4-2",
    "soundNameCategory": "Gliding Pulse Lead I",
    "notesDescription": "Gliding Pulse Lead I: Wide LFO Filter Sweep for low Filter/Envelope values",
    "waveformOscType": "Fixed + Sub 25%",
    "filterFreq": "High",
    "resonance": "High",
    "envMod": "x",
    "attack": "None",
    "decay": "Fast",
    "sustain": "High",
    "release": "None",
    "chorus": "I",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "4 - 3",
    "glide": "x",
    "octave": "0",
    "rate": "Slow",
    "delay": "x",
    "lfo": "x",
    "pwm": "LFO",
    "pulse": "PWM",
    "saw": "x",
    "sub": "x",
    "noise": "x",
    "blank_2": "x",
    "freq": "High",
    "res": "Low",
    "env": "x",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Fast",
    "s_control_range": "High",
    "r": "Fast",
    "blank_3": "II",
    "notes_description": "Slow PWM Lead:",
    "bankPatch": "4-3",
    "soundNameCategory": "Slow PWM Lead",
    "notesDescription": "Slow PWM Lead:",
    "waveformOscType": "LFO + PWM",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "x",
    "attack": "None",
    "decay": "Fast",
    "sustain": "High",
    "release": "Fast",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "4 - 4",
    "glide": "x",
    "octave": "0",
    "rate": "Mid",
    "delay": "Y",
    "lfo": "High",
    "pwm": "x",
    "pulse": "x",
    "saw": "SAW",
    "sub": "x",
    "noise": "x",
    "blank_2": "x",
    "freq": "High",
    "res": "Mid",
    "env": "+ Mid",
    "lfo_2": "x",
    "kybd": "x",
    "env_gate": "Env",
    "a": "None",
    "d": "Fast",
    "s_control_range": "High",
    "r": "Fast",
    "blank_3": "II",
    "notes_description": "Vibrato Saw Lead:",
    "bankPatch": "4-4",
    "soundNameCategory": "Vibrato Saw Lead",
    "notesDescription": "Vibrato Saw Lead:",
    "waveformOscType": "Saw + High",
    "filterFreq": "High",
    "resonance": "Mid",
    "envMod": "+ Mid",
    "attack": "None",
    "decay": "Fast",
    "sustain": "High",
    "release": "Fast",
    "chorus": "II",
    "delayReverb": "Y"
  },
  {
    "blank": "",
    "preset": "4 - 5",
    "glide": "Mid",
    "octave": "0",
    "rate": "Fast",
    "delay": "x",
    "lfo": "Low",
    "pwm": "Fixed",
    "pulse": "25%",
    "saw": "x",
    "sub": "x",
    "noise": "x",
    "blank_2": "x",
    "freq": "High",
    "res": "Low",
    "env": "+ High",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Fast",
    "s_control_range": "High",
    "r": "None",
    "blank_3": "II",
    "notes_description": "Gliding Pluse Lead II:",
    "bankPatch": "4-5",
    "soundNameCategory": "Gliding Pluse Lead II",
    "notesDescription": "Gliding Pluse Lead II:",
    "waveformOscType": "Fixed + Sub 25% + Low",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "+ High",
    "attack": "None",
    "decay": "Fast",
    "sustain": "High",
    "release": "None",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "4 - 6",
    "glide": "x",
    "octave": "",
    "rate": "Fast",
    "delay": "Y",
    "lfo": "Mid",
    "pwm": "Fixed",
    "pulse": "25%",
    "saw": "SAW",
    "sub": "x",
    "noise": "x",
    "blank_2": "Y",
    "freq": "High",
    "res": "Mid",
    "env": "+ Mid",
    "lfo_2": "x",
    "kybd": "x",
    "env_gate": "Env",
    "a": "Fast",
    "d": "Fast",
    "s_control_range": "High",
    "r": "Fast",
    "blank_3": "II",
    "notes_description": "Octave Dirty Strings:",
    "bankPatch": "4-6",
    "soundNameCategory": "Octave Dirty Strings",
    "notesDescription": "Octave Dirty Strings:",
    "waveformOscType": "Saw + Fixed + Sub 25% + Mid",
    "filterFreq": "High",
    "resonance": "Mid",
    "envMod": "+ Mid",
    "attack": "Fast",
    "decay": "Fast",
    "sustain": "High",
    "release": "Fast",
    "chorus": "II",
    "delayReverb": "Y"
  },
  {
    "blank": "",
    "preset": "4 - 7",
    "glide": "x",
    "octave": "0",
    "rate": "x",
    "delay": "x",
    "lfo": "x",
    "pwm": "Fixed",
    "pulse": "25%",
    "saw": "SAW",
    "sub": "x",
    "noise": "x",
    "blank_2": "Y",
    "freq": "High",
    "res": "Low",
    "env": "+ Low",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Fast",
    "s_control_range": "High",
    "r": "Fast",
    "blank_3": "II",
    "notes_description": "Octave Mixed Lead:",
    "bankPatch": "4-7",
    "soundNameCategory": "Octave Mixed Lead",
    "notesDescription": "Octave Mixed Lead:",
    "waveformOscType": "Saw + Fixed + Sub 25%",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "+ Low",
    "attack": "None",
    "decay": "Fast",
    "sustain": "High",
    "release": "Fast",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "4 - 8",
    "glide": "x",
    "octave": "+1",
    "rate": "x",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "SQU",
    "saw": "x",
    "sub": "100%",
    "noise": "Low",
    "blank_2": "Y",
    "freq": "High",
    "res": "High",
    "env": "- Low",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Mid",
    "d": "Fast",
    "s_control_range": "High",
    "r": "Fast",
    "blank_3": "II",
    "notes_description": "Blown Octave Square:",
    "bankPatch": "4-8",
    "soundNameCategory": "Blown Octave Square",
    "notesDescription": "Blown Octave Square:",
    "waveformOscType": "Sub 100% + Square",
    "filterFreq": "High",
    "resonance": "High",
    "envMod": "- Low",
    "attack": "Mid",
    "decay": "Fast",
    "sustain": "High",
    "release": "Fast",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "5 - 1",
    "glide": "x",
    "octave": "0",
    "rate": "Mid",
    "delay": "x",
    "lfo": "x",
    "pwm": "LFO",
    "pulse": "PWM",
    "saw": "SAW",
    "sub": "x",
    "noise": "x",
    "blank_2": "Y",
    "freq": "High",
    "res": "Mid",
    "env": "+ Mid",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Fast",
    "d": "Mid",
    "s_control_range": "High (Mid -> High)",
    "r": "Fast",
    "blank_3": "I",
    "notes_description": "Thick Attack Lead:",
    "bankPatch": "5-1",
    "soundNameCategory": "Thick Attack Lead",
    "notesDescription": "Thick Attack Lead:",
    "waveformOscType": "Saw + LFO + PWM",
    "filterFreq": "High",
    "resonance": "Mid",
    "envMod": "+ Mid",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "High (Mid -> High)",
    "release": "Fast",
    "chorus": "I",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "5 - 2",
    "glide": "x",
    "octave": "0",
    "rate": "Mid",
    "delay": "x",
    "lfo": "Low",
    "pwm": "Fixed",
    "pulse": "25%",
    "saw": "SAW",
    "sub": "x",
    "noise": "x",
    "blank_2": "Y",
    "freq": "Mid",
    "res": "Mid",
    "env": "x",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Mid",
    "s_control_range": "High (Mid -> High)",
    "r": "Mid",
    "blank_3": "Off",
    "notes_description": "The Fake Slim Shady:",
    "bankPatch": "5-2",
    "soundNameCategory": "The Fake Slim Shady",
    "notesDescription": "The Fake Slim Shady:",
    "waveformOscType": "Saw + Fixed + Sub 25% + Low",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "x",
    "attack": "None",
    "decay": "Mid",
    "sustain": "High (Mid -> High)",
    "release": "Mid",
    "chorus": "Off",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "5 - 3",
    "glide": "x",
    "octave": "0",
    "rate": "Slow",
    "delay": "x",
    "lfo": "x",
    "pwm": "LFO",
    "pulse": "PWM",
    "saw": "SAW",
    "sub": "x",
    "noise": "Low",
    "blank_2": "Y",
    "freq": "Mid",
    "res": "High",
    "env": "x",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Fast",
    "d": "Mid",
    "s_control_range": "High",
    "r": "Slow",
    "blank_3": "II",
    "notes_description": "Ya-ee Choir:",
    "bankPatch": "5-3",
    "soundNameCategory": "Ya-ee Choir",
    "notesDescription": "Ya-ee Choir:",
    "waveformOscType": "Saw + LFO + PWM",
    "filterFreq": "Mid",
    "resonance": "High",
    "envMod": "x",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "High",
    "release": "Slow",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "5 - 4",
    "glide": "x",
    "octave": "0",
    "rate": "x",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "x",
    "saw": "SAW",
    "sub": "50%",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Mid",
    "env": "+ Low",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Fast",
    "d": "Mid",
    "s_control_range": "High (Mid -> High)",
    "r": "Mid",
    "blank_3": "II",
    "notes_description": "Dark Strings:",
    "bankPatch": "5-4",
    "soundNameCategory": "Dark Strings",
    "notesDescription": "Dark Strings:",
    "waveformOscType": "Saw + Sub 50%",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "+ Low",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "High (Mid -> High)",
    "release": "Mid",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "5 - 5",
    "glide": "Slow",
    "octave": "+1",
    "rate": "Fast",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "x",
    "saw": "SAW",
    "sub": "100%",
    "noise": "Mid",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Mid",
    "env": "+ High",
    "lfo_2": "High",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Fast",
    "d": "Mid",
    "s_control_range": "High (Mid -> High)",
    "r": "Mid",
    "blank_3": "II",
    "notes_description": "Angry Cat: Gliding noisy lead with fast filter modulation",
    "bankPatch": "5-5",
    "soundNameCategory": "Angry Cat",
    "notesDescription": "Angry Cat: Gliding noisy lead with fast filter modulation",
    "waveformOscType": "Saw + Sub 100%",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "+ High",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "High (Mid -> High)",
    "release": "Mid",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "5 - 6",
    "glide": "x",
    "octave": "0",
    "rate": "Mid",
    "delay": "x",
    "lfo": "x",
    "pwm": "LFO",
    "pulse": "PWM",
    "saw": "x",
    "sub": "x",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Mid",
    "env": "+ Mid",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Mid",
    "d": "Mid",
    "s_control_range": "High (Mid -> High)",
    "r": "Mid",
    "blank_3": "II",
    "notes_description": "Brass Choir:",
    "bankPatch": "5-6",
    "soundNameCategory": "Brass Choir",
    "notesDescription": "Brass Choir:",
    "waveformOscType": "LFO + PWM",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "+ Mid",
    "attack": "Mid",
    "decay": "Mid",
    "sustain": "High (Mid -> High)",
    "release": "Mid",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "5 - 7",
    "glide": "Fast",
    "octave": "+1",
    "rate": "Mid",
    "delay": "x",
    "lfo": "x",
    "pwm": "Fixed",
    "pulse": "25%",
    "saw": "x",
    "sub": "100%",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "High",
    "env": "+ Low",
    "lfo_2": "Low",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Mid",
    "d": "Mid",
    "s_control_range": "High (Mid -> High)",
    "r": "Fast",
    "blank_3": "Off",
    "notes_description": "Whoa Flute:",
    "bankPatch": "5-7",
    "soundNameCategory": "Whoa Flute",
    "notesDescription": "Whoa Flute:",
    "waveformOscType": "Sub 100% + Fixed + Sub 25%",
    "filterFreq": "Mid",
    "resonance": "High",
    "envMod": "+ Low",
    "attack": "Mid",
    "decay": "Mid",
    "sustain": "High (Mid -> High)",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "5 - 8",
    "glide": "x",
    "octave": "+1",
    "rate": "Slow",
    "delay": "x",
    "lfo": "x",
    "pwm": "LFO",
    "pulse": "PWM",
    "saw": "x",
    "sub": "100%",
    "noise": "Low",
    "blank_2": "x",
    "freq": "Low",
    "res": "Low",
    "env": "+ High",
    "lfo_2": "Mid",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Mid",
    "s_control_range": "High (Low -> High)",
    "r": "None",
    "blank_3": "II",
    "notes_description": "Honky Tonk Clav: (Great bass sounds)",
    "bankPatch": "5-8",
    "soundNameCategory": "Honky Tonk Clav",
    "notesDescription": "Honky Tonk Clav: (Great bass sounds)",
    "waveformOscType": "Sub 100% + LFO + PWM",
    "filterFreq": "Low",
    "resonance": "Low",
    "envMod": "+ High",
    "attack": "None",
    "decay": "Mid",
    "sustain": "High (Low -> High)",
    "release": "None",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "6 - 1",
    "glide": "x",
    "octave": "0",
    "rate": "x",
    "delay": "x",
    "lfo": "x",
    "pwm": "Env",
    "pulse": "PWM",
    "saw": "x",
    "sub": "x",
    "noise": "x",
    "blank_2": "x",
    "freq": "High",
    "res": "Low",
    "env": "+ Low",
    "lfo_2": "x",
    "kybd": "x",
    "env_gate": "Env/Gate",
    "a": "None",
    "d": "Mid",
    "s_control_range": "High (Mid -> High)",
    "r": "None",
    "blank_3": "I",
    "notes_description": "PWM Envelope: VCA Gate for low Envelope settings, VCA Env for high Envelope settings",
    "bankPatch": "6-1",
    "soundNameCategory": "PWM Envelope",
    "notesDescription": "PWM Envelope: VCA Gate for low Envelope settings, VCA Env for high Envelope settings",
    "waveformOscType": "Env + PWM",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "+ Low",
    "attack": "None",
    "decay": "Mid",
    "sustain": "High (Mid -> High)",
    "release": "None",
    "chorus": "I",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "6 - 2",
    "glide": "x",
    "octave": "0",
    "rate": "Mid",
    "delay": "Y",
    "lfo": "Mid",
    "pwm": "x",
    "pulse": "x",
    "saw": "SAW",
    "sub": "x",
    "noise": "x",
    "blank_2": "Y",
    "freq": "Mid",
    "res": "Low",
    "env": "x",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Fast",
    "d": "Mid",
    "s_control_range": "High",
    "r": "Mid",
    "blank_3": "Off",
    "notes_description": "Solo String:",
    "bankPatch": "6-2",
    "soundNameCategory": "Solo String",
    "notesDescription": "Solo String:",
    "waveformOscType": "Saw + Mid",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "x",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "High",
    "release": "Mid",
    "chorus": "Off",
    "delayReverb": "Y"
  },
  {
    "blank": "",
    "preset": "6 - 3",
    "glide": "x",
    "octave": "0",
    "rate": "Max",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "SQU",
    "saw": "x",
    "sub": "100%",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Mid",
    "env": "x",
    "lfo_2": "High",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Mid",
    "s_control_range": "High",
    "r": "Fast",
    "blank_3": "II",
    "notes_description": "Square Ring Mod:",
    "bankPatch": "6-3",
    "soundNameCategory": "Square Ring Mod",
    "notesDescription": "Square Ring Mod:",
    "waveformOscType": "Sub 100% + Square",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "x",
    "attack": "None",
    "decay": "Mid",
    "sustain": "High",
    "release": "Fast",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "6 - 4",
    "glide": "x",
    "octave": "0",
    "rate": "Mid",
    "delay": "Y",
    "lfo": "x",
    "pwm": "x",
    "pulse": "x",
    "saw": "SAW",
    "sub": "x",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Low",
    "env": "+ High",
    "lfo_2": "Mid",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Mid",
    "d": "Mid",
    "s_control_range": "High (Low -> High)",
    "r": "Fast",
    "blank_3": "Off",
    "notes_description": "Mellow Trumpet:",
    "bankPatch": "6-4",
    "soundNameCategory": "Mellow Trumpet",
    "notesDescription": "Mellow Trumpet:",
    "waveformOscType": "Saw",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "+ High",
    "attack": "Mid",
    "decay": "Mid",
    "sustain": "High (Low -> High)",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Y"
  },
  {
    "blank": "",
    "preset": "6 - 5",
    "glide": "x",
    "octave": "0",
    "rate": "Mid",
    "delay": "Y",
    "lfo": "x",
    "pwm": "x",
    "pulse": "x",
    "saw": "SAW",
    "sub": "x",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Low",
    "env": "x",
    "lfo_2": "High",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Fast",
    "d": "Mid",
    "s_control_range": "High (Mid -> High)",
    "r": "Fast",
    "blank_3": "Off",
    "notes_description": "Horn:",
    "bankPatch": "6-5",
    "soundNameCategory": "Horn",
    "notesDescription": "Horn:",
    "waveformOscType": "Saw",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "x",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "High (Mid -> High)",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Y"
  },
  {
    "blank": "",
    "preset": "6 - 6",
    "glide": "x",
    "octave": "0",
    "rate": "x",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "SQU",
    "saw": "x",
    "sub": "x",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Mid",
    "env": "+ High",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env/Gate",
    "a": "None",
    "d": "Mid",
    "s_control_range": "High (Low -> High)",
    "r": "None",
    "blank_3": "I",
    "notes_description": "Square Chorus Lead: VCA Gate for low Envelope settings, VCA Env for high Envelope settings",
    "bankPatch": "6-6",
    "soundNameCategory": "Square Chorus Lead",
    "notesDescription": "Square Chorus Lead: VCA Gate for low Envelope settings, VCA Env for high Envelope settings",
    "waveformOscType": "Square",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "+ High",
    "attack": "None",
    "decay": "Mid",
    "sustain": "High (Low -> High)",
    "release": "None",
    "chorus": "I",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "6 - 7",
    "glide": "x",
    "octave": "0",
    "rate": "Mid",
    "delay": "Y",
    "lfo": "Low",
    "pwm": "x",
    "pulse": "SQU",
    "saw": "x",
    "sub": "x",
    "noise": "x",
    "blank_2": "Y",
    "freq": "Mid",
    "res": "Mid",
    "env": "+ Low",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Fast",
    "d": "Mid",
    "s_control_range": "High (Mid -> High)",
    "r": "Fast",
    "blank_3": "Off",
    "notes_description": "Clarinet:",
    "bankPatch": "6-7",
    "soundNameCategory": "Clarinet",
    "notesDescription": "Clarinet:",
    "waveformOscType": "Square + Low",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "+ Low",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "High (Mid -> High)",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "Y"
  },
  {
    "blank": "",
    "preset": "6 - 8",
    "glide": "x",
    "octave": "0",
    "rate": "Mid",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "x",
    "saw": "x",
    "sub": "x",
    "noise": "High",
    "blank_2": "Y",
    "freq": "Tuned*",
    "res": "Max*",
    "env": "x",
    "lfo_2": "Low",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Fast",
    "d": "Mid",
    "s_control_range": "High (Mid -> High)",
    "r": "Fast",
    "blank_3": "Off",
    "notes_description": "Ocarina: Keyboard tracked self-oscilating filtered noise (Turn down Resonance to increase noise)",
    "bankPatch": "6-8",
    "soundNameCategory": "Ocarina",
    "notesDescription": "Ocarina: Keyboard tracked self-oscilating filtered noise (Turn down Resonance to increase noise)",
    "waveformOscType": "Unknown",
    "filterFreq": "Tuned*",
    "resonance": "Max*",
    "envMod": "x",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "High (Mid -> High)",
    "release": "Fast",
    "chorus": "Off",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "7 - 1",
    "glide": "x",
    "octave": "+1",
    "rate": "Mid",
    "delay": "x",
    "lfo": "x",
    "pwm": "LFO",
    "pulse": "PWM",
    "saw": "x",
    "sub": "100%",
    "noise": "x",
    "blank_2": "x",
    "freq": "High",
    "res": "Low",
    "env": "+ Low",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Fast",
    "d": "Mid",
    "s_control_range": "High",
    "r": "Mid",
    "blank_3": "II",
    "notes_description": "PWM String Ensemble I:",
    "bankPatch": "7-1",
    "soundNameCategory": "PWM String Ensemble I",
    "notesDescription": "PWM String Ensemble I:",
    "waveformOscType": "Sub 100% + LFO + PWM",
    "filterFreq": "High",
    "resonance": "Low",
    "envMod": "+ Low",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "High",
    "release": "Mid",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "7 - 2",
    "glide": "x",
    "octave": "+1",
    "rate": "x",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "x",
    "saw": "SAW",
    "sub": "100%",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Mid",
    "env": "x",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Fast",
    "d": "Mid",
    "s_control_range": "High",
    "r": "Mid",
    "blank_3": "II",
    "notes_description": "Saw String Ensemble:",
    "bankPatch": "7-2",
    "soundNameCategory": "Saw String Ensemble",
    "notesDescription": "Saw String Ensemble:",
    "waveformOscType": "Saw + Sub 100%",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "x",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "High",
    "release": "Mid",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "7 - 3",
    "glide": "x",
    "octave": "+1",
    "rate": "Mid",
    "delay": "x",
    "lfo": "Low",
    "pwm": "x",
    "pulse": "x",
    "saw": "SAW",
    "sub": "100%",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Mid",
    "env": "+ Low",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Mid",
    "d": "Mid",
    "s_control_range": "High (Mid -> High)",
    "r": "Mid",
    "blank_3": "II",
    "notes_description": "Brass Ensemble:",
    "bankPatch": "7-3",
    "soundNameCategory": "Brass Ensemble",
    "notesDescription": "Brass Ensemble:",
    "waveformOscType": "Saw + Sub 100% + Low",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "+ Low",
    "attack": "Mid",
    "decay": "Mid",
    "sustain": "High (Mid -> High)",
    "release": "Mid",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "7 - 4",
    "glide": "x",
    "octave": "+1",
    "rate": "Mid",
    "delay": "x",
    "lfo": "x",
    "pwm": "LFO",
    "pulse": "PWM",
    "saw": "x",
    "sub": "100%",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Mid",
    "env": "x",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Fast",
    "d": "Mid",
    "s_control_range": "High",
    "r": "Slow",
    "blank_3": "II",
    "notes_description": "PWM String Ensemble II:",
    "bankPatch": "7-4",
    "soundNameCategory": "PWM String Ensemble II",
    "notesDescription": "PWM String Ensemble II:",
    "waveformOscType": "Sub 100% + LFO + PWM",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "x",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "High",
    "release": "Slow",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "7 - 5",
    "glide": "x",
    "octave": "0",
    "rate": "Fast",
    "delay": "x",
    "lfo": "Low",
    "pwm": "x",
    "pulse": "x",
    "saw": "SAW",
    "sub": "25%",
    "noise": "Mid",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Mid",
    "env": "x",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Mid",
    "d": "Mid",
    "s_control_range": "High",
    "r": "Mid",
    "blank_3": "I",
    "notes_description": "Ghost Pad: (Open filter for Noisy String Ensemble)",
    "bankPatch": "7-5",
    "soundNameCategory": "Ghost Pad",
    "notesDescription": "Ghost Pad: (Open filter for Noisy String Ensemble)",
    "waveformOscType": "Saw + Sub 25% + Low",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "x",
    "attack": "Mid",
    "decay": "Mid",
    "sustain": "High",
    "release": "Mid",
    "chorus": "I",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "7 - 6",
    "glide": "x",
    "octave": "0",
    "rate": "Mid",
    "delay": "Y",
    "lfo": "x",
    "pwm": "Fixed",
    "pulse": "20%",
    "saw": "x",
    "sub": "x",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Low",
    "env": "- Low",
    "lfo_2": "High",
    "kybd": "x",
    "env_gate": "Env",
    "a": "Fast",
    "d": "Mid",
    "s_control_range": "High (Mid -> High)",
    "r": "Mid",
    "blank_3": "II",
    "notes_description": "Evolving Filter Pad I (Bright):",
    "bankPatch": "7-6",
    "soundNameCategory": "Evolving Filter Pad I (Bright)",
    "notesDescription": "Evolving Filter Pad I (Bright):",
    "waveformOscType": "Fixed + Sub 20%",
    "filterFreq": "Mid",
    "resonance": "Low",
    "envMod": "- Low",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "High (Mid -> High)",
    "release": "Mid",
    "chorus": "II",
    "delayReverb": "Y"
  },
  {
    "blank": "",
    "preset": "7 - 7",
    "glide": "x",
    "octave": "0",
    "rate": "Mid",
    "delay": "Y",
    "lfo": "x",
    "pwm": "Fixed",
    "pulse": "25%",
    "saw": "x",
    "sub": "x",
    "noise": "x",
    "blank_2": "Y",
    "freq": "Mid",
    "res": "High",
    "env": "+ Low",
    "lfo_2": "High",
    "kybd": "x",
    "env_gate": "Env",
    "a": "Mid",
    "d": "Mid",
    "s_control_range": "High",
    "r": "Slow",
    "blank_3": "II",
    "notes_description": "Evolving Filter Pad II (Mellow):",
    "bankPatch": "7-7",
    "soundNameCategory": "Evolving Filter Pad II (Mellow)",
    "notesDescription": "Evolving Filter Pad II (Mellow):",
    "waveformOscType": "Fixed + Sub 25%",
    "filterFreq": "Mid",
    "resonance": "High",
    "envMod": "+ Low",
    "attack": "Mid",
    "decay": "Mid",
    "sustain": "High",
    "release": "Slow",
    "chorus": "II",
    "delayReverb": "Y"
  },
  {
    "blank": "",
    "preset": "7 - 8",
    "glide": "x",
    "octave": "0",
    "rate": "Slow",
    "delay": "x",
    "lfo": "x",
    "pwm": "Fixed",
    "pulse": "20%",
    "saw": "x",
    "sub": "x",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Mid",
    "env": "- Med",
    "lfo_2": "High",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Fast",
    "d": "Mid",
    "s_control_range": "High (Mid -> High)",
    "r": "Slow",
    "blank_3": "II",
    "notes_description": "Evolving Filter Pad III (Mellow Slow and Wide):",
    "bankPatch": "7-8",
    "soundNameCategory": "Evolving Filter Pad III (Mellow Slow and Wide)",
    "notesDescription": "Evolving Filter Pad III (Mellow Slow and Wide):",
    "waveformOscType": "Fixed + Sub 20%",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "- Med",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "High (Mid -> High)",
    "release": "Slow",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "8 - 1",
    "glide": "x",
    "octave": "+1",
    "rate": "Slow",
    "delay": "x",
    "lfo": "x",
    "pwm": "Fixed",
    "pulse": "20%",
    "saw": "x",
    "sub": "50%",
    "noise": "Low",
    "blank_2": "x",
    "freq": "Mid",
    "res": "High",
    "env": "- Med",
    "lfo_2": "High",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Fast",
    "d": "Mid",
    "s_control_range": "High (Mid -> High)",
    "r": "Mid",
    "blank_3": "II",
    "notes_description": "Evolving Filter Pad IV (Bright Slow and Wide):",
    "bankPatch": "8-1",
    "soundNameCategory": "Evolving Filter Pad IV (Bright Slow and Wide)",
    "notesDescription": "Evolving Filter Pad IV (Bright Slow and Wide):",
    "waveformOscType": "Sub 50% + Fixed + Sub 20%",
    "filterFreq": "Mid",
    "resonance": "High",
    "envMod": "- Med",
    "attack": "Fast",
    "decay": "Mid",
    "sustain": "High (Mid -> High)",
    "release": "Mid",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "8 - 2",
    "glide": "Mid",
    "octave": "0",
    "rate": "Mid",
    "delay": "x",
    "lfo": "x",
    "pwm": "LFO",
    "pulse": "PWM",
    "saw": "x",
    "sub": "x",
    "noise": "x",
    "blank_2": "x",
    "freq": "High",
    "res": "High",
    "env": "- Low",
    "lfo_2": "High",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Mid",
    "d": "Mid",
    "s_control_range": "High (Mid -> High)",
    "r": "Mid",
    "blank_3": "II",
    "notes_description": "Evolving Filter Pad V (Squishy I):",
    "bankPatch": "8-2",
    "soundNameCategory": "Evolving Filter Pad V (Squishy I)",
    "notesDescription": "Evolving Filter Pad V (Squishy I):",
    "waveformOscType": "LFO + PWM",
    "filterFreq": "High",
    "resonance": "High",
    "envMod": "- Low",
    "attack": "Mid",
    "decay": "Mid",
    "sustain": "High (Mid -> High)",
    "release": "Mid",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "8 - 3",
    "glide": "x",
    "octave": "0",
    "rate": "Slow",
    "delay": "Y",
    "lfo": "x",
    "pwm": "Fixed",
    "pulse": "20%",
    "saw": "x",
    "sub": "x",
    "noise": "x",
    "blank_2": "x",
    "freq": "High",
    "res": "Mid",
    "env": "- Low",
    "lfo_2": "High",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Mid",
    "d": "Mid",
    "s_control_range": "High (Mid -> High)",
    "r": "Mid",
    "blank_3": "I",
    "notes_description": "Evolving Filter Pad VI (Squishy II):",
    "bankPatch": "8-3",
    "soundNameCategory": "Evolving Filter Pad VI (Squishy II)",
    "notesDescription": "Evolving Filter Pad VI (Squishy II):",
    "waveformOscType": "Fixed + Sub 20%",
    "filterFreq": "High",
    "resonance": "Mid",
    "envMod": "- Low",
    "attack": "Mid",
    "decay": "Mid",
    "sustain": "High (Mid -> High)",
    "release": "Mid",
    "chorus": "I",
    "delayReverb": "Y"
  },
  {
    "blank": "",
    "preset": "8 - 4",
    "glide": "x",
    "octave": "+1",
    "rate": "Slow",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "x",
    "saw": "SAW",
    "sub": "50%",
    "noise": "x",
    "blank_2": "x",
    "freq": "Low",
    "res": "Mid",
    "env": "+ High",
    "lfo_2": "Mid",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Slow",
    "d": "Mid",
    "s_control_range": "High (Low -> High)",
    "r": "Mid",
    "blank_3": "II",
    "notes_description": "Evolving Filter Pad VII (Blossoming I):",
    "bankPatch": "8-4",
    "soundNameCategory": "Evolving Filter Pad VII (Blossoming I)",
    "notesDescription": "Evolving Filter Pad VII (Blossoming I):",
    "waveformOscType": "Saw + Sub 50%",
    "filterFreq": "Low",
    "resonance": "Mid",
    "envMod": "+ High",
    "attack": "Slow",
    "decay": "Mid",
    "sustain": "High (Low -> High)",
    "release": "Mid",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "8 - 5",
    "glide": "x",
    "octave": "0",
    "rate": "x",
    "delay": "x",
    "lfo": "x",
    "pwm": "Env",
    "pulse": "PWM",
    "saw": "x",
    "sub": "x",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "High",
    "env": "+ Low",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Slow",
    "d": "Mid",
    "s_control_range": "High (Mid -> High)",
    "r": "Slow",
    "blank_3": "I",
    "notes_description": "Evolving Filter Pad VII (Blossoming II):",
    "bankPatch": "8-5",
    "soundNameCategory": "Evolving Filter Pad VII (Blossoming II)",
    "notesDescription": "Evolving Filter Pad VII (Blossoming II):",
    "waveformOscType": "Env + PWM",
    "filterFreq": "Mid",
    "resonance": "High",
    "envMod": "+ Low",
    "attack": "Slow",
    "decay": "Mid",
    "sustain": "High (Mid -> High)",
    "release": "Slow",
    "chorus": "I",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "8 - 6",
    "glide": "x",
    "octave": "+1",
    "rate": "Fast",
    "delay": "Y",
    "lfo": "Low",
    "pwm": "Fixed",
    "pulse": "25%",
    "saw": "x",
    "sub": "100%",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "Mid",
    "env": "- Low",
    "lfo_2": "x",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "Mid",
    "d": "Slow",
    "s_control_range": "Off (Off -> High)",
    "r": "Fast",
    "blank_3": "I",
    "notes_description": "Decaying Filter Pad (Blossoming III): Sustains once Envelope control is past 50%",
    "bankPatch": "8-6",
    "soundNameCategory": "Decaying Filter Pad (Blossoming III)",
    "notesDescription": "Decaying Filter Pad (Blossoming III): Sustains once Envelope control is past 50%",
    "waveformOscType": "Sub 100% + Fixed + Sub 25% + Low",
    "filterFreq": "Mid",
    "resonance": "Mid",
    "envMod": "- Low",
    "attack": "Mid",
    "decay": "Slow",
    "sustain": "Off (Off -> High)",
    "release": "Fast",
    "chorus": "I",
    "delayReverb": "Y"
  },
  {
    "blank": "",
    "preset": "8 - 7",
    "glide": "x",
    "octave": "+1",
    "rate": "Mid",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "x",
    "saw": "SAW",
    "sub": "100%",
    "noise": "x",
    "blank_2": "x",
    "freq": "Low",
    "res": "High",
    "env": "+ Low",
    "lfo_2": "High*",
    "kybd": "x",
    "env_gate": "Env",
    "a": "Mid",
    "d": "Mid",
    "s_control_range": "High (Mid -> High)",
    "r": "Slow",
    "blank_3": "II",
    "notes_description": "Sample and Hold Pad: Freerunning S&H LFO to Filter. S&H effect dissapears for high Filter Settings",
    "bankPatch": "8-7",
    "soundNameCategory": "Sample and Hold Pad",
    "notesDescription": "Sample and Hold Pad: Freerunning S&H LFO to Filter. S&H effect dissapears for high Filter Settings",
    "waveformOscType": "Saw + Sub 100%",
    "filterFreq": "Low",
    "resonance": "High",
    "envMod": "+ Low",
    "attack": "Mid",
    "decay": "Mid",
    "sustain": "High (Mid -> High)",
    "release": "Slow",
    "chorus": "II",
    "delayReverb": "x"
  },
  {
    "blank": "",
    "preset": "8 - 8",
    "glide": "x",
    "octave": "0",
    "rate": "Fast",
    "delay": "x",
    "lfo": "x",
    "pwm": "x",
    "pulse": "SQU",
    "saw": "SAW",
    "sub": "x",
    "noise": "x",
    "blank_2": "x",
    "freq": "Mid",
    "res": "High",
    "env": "x",
    "lfo_2": "Low*",
    "kybd": "Y",
    "env_gate": "Env",
    "a": "None",
    "d": "Mid",
    "s_control_range": "High (Low -> High)",
    "r": "Slow",
    "blank_3": "II",
    "notes_description": "Plectrum Tremolo Pad: Freerunning SAW LFO to Filter. Tremolo effect dissapears for high Filter Settings",
    "bankPatch": "8-8",
    "soundNameCategory": "Plectrum Tremolo Pad",
    "notesDescription": "Plectrum Tremolo Pad: Freerunning SAW LFO to Filter. Tremolo effect dissapears for high Filter Settings",
    "waveformOscType": "Saw + Square",
    "filterFreq": "Mid",
    "resonance": "High",
    "envMod": "x",
    "attack": "None",
    "decay": "Mid",
    "sustain": "High (Low -> High)",
    "release": "Slow",
    "chorus": "II",
    "delayReverb": "x"
  }
];
